{
  description = "A Wayland-native screensaver for Hyprland — fractal shaders on wlr-layer-shell overlays";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, rust-overlay }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];

      forAllSystems = nixpkgs.lib.genAttrs systems;

      pkgsFor = system: import nixpkgs {
        inherit system;
        overlays = [ rust-overlay.overlays.default ];
      };

      # System libraries required to build and run hyprsaver.
      buildInputsFor = pkgs: with pkgs; [
        wayland
        wayland-protocols
        libGL
        libxkbcommon
        mesa
      ];

      nativeBuildInputsFor = pkgs: with pkgs; [
        pkg-config
        cmake
      ];

    in {

      # ── packages ────────────────────────────────────────────────────────────

      packages = forAllSystems (system:
        let pkgs = pkgsFor system;
        in {
          default = pkgs.rustPlatform.buildRustPackage {
            pname = "hyprsaver";
            version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package.version;

            src = ./.;

            cargoLock.lockFile = ./Cargo.lock;

            nativeBuildInputs = nativeBuildInputsFor pkgs;
            buildInputs = buildInputsFor pkgs;

            # wayland-egl is provided by the wayland package; mesa supplies EGL.
            PKG_CONFIG_PATH = with pkgs; lib.makeSearchPathOutput "dev" "lib/pkgconfig" [
              wayland
              mesa
              libxkbcommon
            ];

            postInstall = ''
              # Install example configs and assets.
              install -dm755 $out/share/hyprsaver/examples
              cp -r examples/palettes $out/share/hyprsaver/examples/
              install -Dm644 examples/palette_test.frag \
                $out/share/hyprsaver/examples/palette_test.frag
              install -Dm644 config.example.toml \
                $out/share/hyprsaver/examples/config.example.toml

              # Install man page if present (generated by a future release task).
              if [ -f doc/hyprsaver.1 ]; then
                install -Dm644 doc/hyprsaver.1 $out/share/man/man1/hyprsaver.1
              fi
            '';

            meta = with pkgs.lib; {
              description = "A Wayland-native screensaver for Hyprland — fractal shaders on wlr-layer-shell overlays";
              longDescription = ''
                hyprsaver renders GLSL fragment shaders as fullscreen overlays on every
                connected monitor using the wlr-layer-shell Wayland protocol.  It is
                designed to complement hyprlock and hypridle.
              '';
              homepage = "https://github.com/maravexa/hyprsaver";
              license = licenses.mit;
              maintainers = [ ];
              platforms = platforms.linux;
              mainProgram = "hyprsaver";
            };
          };
        }
      );

      # ── devShells ────────────────────────────────────────────────────────────

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system;
        in {
          default = pkgs.mkShell {
            nativeBuildInputs = (nativeBuildInputsFor pkgs) ++ (with pkgs; [
              # Pinned stable Rust with the extras needed for day-to-day work.
              (rust-bin.stable.latest.default.override {
                extensions = [ "rust-src" "rustfmt" "clippy" "rust-analyzer" ];
              })
            ]);

            buildInputs = buildInputsFor pkgs;

            PKG_CONFIG_PATH = with pkgs; lib.makeSearchPathOutput "dev" "lib/pkgconfig" [
              wayland
              mesa
              libxkbcommon
            ];

            # libGL / EGL are dlopen'd at runtime on NixOS and won't be found
            # unless LD_LIBRARY_PATH includes the Nix store paths.
            shellHook = ''
              export LD_LIBRARY_PATH="${pkgs.lib.makeLibraryPath (buildInputsFor pkgs)}:''${LD_LIBRARY_PATH:-}"
              echo "hyprsaver dev shell — $(rustc --version 2>/dev/null || echo 'rustc not on PATH yet')"
            '';
          };
        }
      );

      # ── overlays ─────────────────────────────────────────────────────────────

      overlays.default = final: _prev: {
        hyprsaver = self.packages.${final.system}.default;
      };

    };
}
